import { SimulationClient } from "@/components/simulation-client";

export const dynamic = "force-dynamic";

export default function GamePage() {
  return (
    <main className="mx-auto w-full max-w-7xl px-4 py-8 md:px-8 md:py-12">
      <header className="mb-8 grid gap-3">
        <p className="text-xs uppercase tracking-[0.22em] text-amber-300/90">
          AI Benchmark Arena
        </p>
        <h1 className="text-3xl font-semibold text-stone-100 md:text-4xl">
          Model vs Model Chess Simulation
        </h1>
        <p className="max-w-3xl text-stone-300">
          Every turn is generated by an OpenRouter model, validated by chess.js, and
          persisted to NeonDB. The server executes one move per request to stay
          serverless-safe.
        </p>
      </header>

      <SimulationClient />
    </main>
  );
}
