import Link from "next/link";
import { SimulationClient } from "@/components/simulation-client";

export const dynamic = "force-dynamic";

export default function GamePage() {
  return (
    <main
      style={{
        maxWidth: 1280,
        margin: "0 auto",
        padding: "48px 24px 80px",
        width: "100%",
      }}
    >
      {/* Page header */}
      <header className="animate-enter" style={{ marginBottom: 40 }}>
        <p
          style={{
            fontSize: 11,
            fontWeight: 600,
            letterSpacing: "0.13em",
            textTransform: "uppercase",
            color: "var(--accent)",
            marginBottom: 10,
          }}
        >
          AI Benchmark Arena
        </p>
        <h1
          style={{
            fontFamily: "var(--font-playfair), Georgia, serif",
            fontSize: "clamp(26px, 3.5vw, 38px)",
            fontWeight: 600,
            color: "var(--text-primary)",
            letterSpacing: "-0.02em",
            marginBottom: 10,
          }}
        >
          Model vs Model Simulation
        </h1>
        <p style={{ fontSize: 14.5, color: "var(--text-secondary)", maxWidth: 580 }}>
          Each turn is generated by an OpenRouter model, validated by chess.js,
          and persisted to NeonDB with one move per serverless request.
        </p>
      </header>

      <div className="animate-enter-delay-1">
        <SimulationClient />
      </div>
    </main>
  );
}
