import Link from "next/link";

const features = [
  "AI vs AI turn-based orchestration",
  "NeonDB state persistence (FEN + move history)",
  "Strict move legality via chess.js",
  "Deterministic fallback for invalid model output",
  "Live leaderboard with confidence-adjusted ranking",
];

export default function Home() {
  return (
    <main className="mx-auto flex w-full max-w-7xl flex-1 flex-col px-4 py-10 md:px-8 md:py-14">
      <section className="relative overflow-hidden rounded-3xl border border-stone-700/50 bg-[radial-gradient(circle_at_top_left,rgba(184,134,11,0.2),transparent_45%),radial-gradient(circle_at_80%_20%,rgba(56,189,248,0.16),transparent_40%),rgba(10,10,10,0.75)] p-7 shadow-[0_30px_100px_rgba(0,0,0,0.5)] md:p-10">
        <p className="mb-4 text-xs uppercase tracking-[0.24em] text-amber-300/90">
          AI Benchmarking Platform
        </p>
        <h1 className="max-w-4xl text-4xl font-semibold leading-tight text-stone-100 md:text-6xl">
          Let frontier language models battle in chess, one verified move at a
          time.
        </h1>
        <p className="mt-5 max-w-3xl text-base text-stone-300 md:text-lg">
          This platform executes serverless-safe chess simulations where every move
          is generated by OpenRouter, validated for legality, and persisted for
          transparent benchmarking.
        </p>
        <div className="mt-8 flex flex-wrap gap-3">
          <Link
            href="/game"
            className="rounded-xl bg-amber-400 px-5 py-3 text-sm font-bold uppercase tracking-[0.13em] text-stone-900 transition hover:bg-amber-300"
          >
            Start Simulation
          </Link>
          <Link
            href="/leaderboard"
            className="rounded-xl border border-stone-400 px-5 py-3 text-sm font-bold uppercase tracking-[0.13em] text-stone-100 transition hover:border-stone-200"
          >
            View Leaderboard
          </Link>
        </div>
      </section>

      <section className="mt-8 grid gap-4 md:grid-cols-2">
        {features.map((feature) => (
          <article
            key={feature}
            className="rounded-2xl border border-stone-700/50 bg-stone-950/70 p-5 text-sm uppercase tracking-[0.08em] text-stone-300"
          >
            {feature}
          </article>
        ))}
      </section>
    </main>
  );
}
