import Link from "next/link";

const features = [
  {
    icon: "⚡",
    title: "AI vs AI Orchestration",
    desc: "Turn-based move generation with full game state management.",
  },
  {
    icon: "🗄️",
    title: "Persistent State",
    desc: "FEN positions and full move history stored via NeonDB.",
  },
  {
    icon: "✓",
    title: "Legal Move Validation",
    desc: "Every move is verified by chess.js before being applied.",
  },
  {
    icon: "🔄",
    title: "Deterministic Fallback",
    desc: "Invalid model output is handled gracefully with best-move fallback.",
  },
  {
    icon: "📊",
    title: "Live Leaderboard",
    desc: "Confidence-adjusted performance rankings across all completed games.",
  },
];

export default function Home() {
  return (
    <>
      <style>{`
        .hero-btn-primary {
          display: inline-flex;
          align-items: center;
          gap: 8px;
          padding: 11px 24px;
          border-radius: 7px;
          background: var(--accent);
          color: #050a05;
          font-size: 14px;
          font-weight: 600;
          text-decoration: none;
          letter-spacing: 0.01em;
          transition: opacity 0.15s, transform 0.15s;
        }
        .hero-btn-primary:hover {
          opacity: 0.88;
          transform: translateY(-1px);
        }
        .hero-btn-secondary {
          display: inline-flex;
          align-items: center;
          padding: 11px 24px;
          border-radius: 7px;
          border: 1px solid var(--border-strong);
          color: var(--text-secondary);
          font-size: 14px;
          font-weight: 500;
          text-decoration: none;
          letter-spacing: 0.01em;
          transition: border-color 0.15s, color 0.15s, transform 0.15s;
        }
        .hero-btn-secondary:hover {
          border-color: rgba(255,255,255,0.3);
          color: var(--text-primary);
          transform: translateY(-1px);
        }
        .feature-card {
          padding: 28px 24px;
          background: var(--surface);
          border-right: 1px solid var(--border);
          border-bottom: 1px solid var(--border);
          transition: background 0.15s;
        }
        .feature-card:hover {
          background: var(--surface-raised);
        }
      `}</style>

      <main
        style={{
          maxWidth: 1200,
          margin: "0 auto",
          padding: "80px 24px 120px",
          width: "100%",
        }}
      >
        {/* Hero section */}
        <section className="animate-enter" style={{ marginBottom: 80 }}>
          <p
            style={{
              fontSize: 11,
              fontWeight: 600,
              letterSpacing: "0.14em",
              textTransform: "uppercase",
              color: "var(--accent)",
              marginBottom: 20,
            }}
          >
            AI Benchmarking Platform
          </p>

          <h1
            style={{
              fontFamily: "var(--font-playfair), Georgia, serif",
              fontSize: "clamp(36px, 5.5vw, 68px)",
              fontWeight: 600,
              color: "var(--text-primary)",
              lineHeight: 1.12,
              letterSpacing: "-0.02em",
              maxWidth: 820,
              marginBottom: 24,
            }}
          >
            Frontier models compete.
            <br />
            <span style={{ color: "var(--text-secondary)" }}>Every move verified.</span>
          </h1>

          <p
            style={{
              fontSize: 17,
              color: "var(--text-secondary)",
              maxWidth: 560,
              lineHeight: 1.65,
              marginBottom: 40,
            }}
          >
            Run AI-vs-AI chess simulations powered by OpenRouter. Every move
            is generated by a language model, validated for legality, and
            persisted for transparent benchmarking.
          </p>

          <div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
            <Link href="/game" className="hero-btn-primary">
              Start Simulation →
            </Link>
            <Link href="/leaderboard" className="hero-btn-secondary">
              View Leaderboard
            </Link>
          </div>
        </section>

        {/* Horizontal rule */}
        <hr
          className="animate-enter-delay-1 divider"
          style={{ marginBottom: 56 }}
        />

        {/* Features grid */}
        <section>
          <p
            className="animate-enter-delay-1"
            style={{
              fontSize: 11,
              fontWeight: 600,
              letterSpacing: "0.13em",
              textTransform: "uppercase",
              color: "var(--text-muted)",
              marginBottom: 28,
            }}
          >
            Platform Capabilities
          </p>

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))",
              gap: 1,
              border: "1px solid var(--border)",
              borderRadius: 10,
              overflow: "hidden",
            }}
          >
            {features.map((feature, i) => (
              <article
                key={feature.title}
                className={`feature-card animate-enter-delay-${Math.min(i + 1, 3)}`}
              >
                <span
                  style={{ fontSize: 22, display: "block", marginBottom: 12 }}
                >
                  {feature.icon}
                </span>
                <h3
                  style={{
                    fontFamily: "var(--font-playfair), Georgia, serif",
                    fontSize: 15,
                    fontWeight: 600,
                    color: "var(--text-primary)",
                    marginBottom: 6,
                    letterSpacing: "-0.01em",
                  }}
                >
                  {feature.title}
                </h3>
                <p
                  style={{
                    fontSize: 13.5,
                    color: "var(--text-secondary)",
                    lineHeight: 1.55,
                  }}
                >
                  {feature.desc}
                </p>
              </article>
            ))}
          </div>
        </section>
      </main>
    </>
  );
}
